Ignore links (symlinks/hardlinks)
I use symlinks in my projects to open the same file in multiple tabs in VSCode ( ref https://stackoverflow.com/a/73994770/1067003 for why i need to use symlinks), 
which causes Phan to crash like

$ ./vendor/bin/phan
ERROR: Unable to read file /home/hans/projects/easyad/classes/Controller/System/VitecBooking.2ln.php: SplFileInfo->isFile() is false for SplFileInfo->getType() == 'link'


the easy fix is to just ignore links.